const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');process.env.DB_PATH=path.join(__dirname,'isolated.db');
const app=require(path.join(root,'src/backend/server'));const db=require(path.join(root,'src/backend/db'));
const results=[];function check(name,f){try{f();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
function frontend(file){const els={};const ctx={window:{location:{origin:'http://test'},addEventListener(){}},localStorage:{getItem(){return null}},document:{getElementById(id){return els[id]||(els[id]={value:'',style:{},innerHTML:''});}},console,alert(){},setInterval(){},setTimeout(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);return {ctx,els};}
(async()=>{const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
try{
 const t=db.prepare("SELECT * FROM templates WHERE model='990' AND type='cert'").get();assert(t);
 const mapping=JSON.parse(t.field_mappings);const before=(await (await fetch(base+'/api/published-bundles')).json());
 for(const [model,n]of [['990',9],['POA200',1]]){const b=before.find(x=>x.model_display===model&&x.certTemplate);check(model+' published point count',()=>assert.equal(b.certTemplate.field_mappings.testPoints.length,n));if(b){const {ctx,els}=frontend('src/frontend/app.js');ctx.fixture=b;vm.runInContext('state.activeBundle=fixture;renderTestPoints()',ctx);check(model+' mobile renders all rows with empty actuals',()=>{assert.equal((els['test-points-body'].innerHTML.match(/id="tp-act-/g)||[]).length,n);assert.equal((els['test-points-body'].innerHTML.match(/id="tp-act-[^"]+"[^>]+value=""/g)||[]).length,n);});}}
 const post=async(m,draft)=>{const r=await fetch(base+'/api/templates/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:t.id,model:t.model,type:t.type,filename:t.filename,version:t.version,fieldMappings:m,isDraft:draft})});return {status:r.status,body:await r.json()};};
 const draft={...mapping,targetLabels:['Date:'],probe:'isolated-draft'};const d=await post(draft,true);check('draft save accepted',()=>assert.equal(d.status,200));
 const after=await(await fetch(base+'/api/published-bundles')).json();check('draft does not change published bundles',()=>assert.deepEqual(after,before));
 const listing=await(await fetch(base+'/api/templates')).json();check('admin reads saved draft',()=>assert.equal(listing.find(x=>x.id===t.id).field_mappings.probe,'isolated-draft'));
 const valid=await post(mapping,false);check('formal publish accepted and clears draft',()=>{assert.equal(valid.status,200);assert.equal(db.prepare('select draft_mappings from templates where id=?').get(t.id).draft_mappings,null)});
 const absent=await post({...mapping,tableConfig:null,testPoints:[]},false);check('reject completely missing table',()=>assert.equal(absent.status,400));
 const partial=await post({...mapping,tableConfig:null,testPoints:[{point:1,std:'1',act:''}]},false);check('reject points without writeback columns',()=>assert.equal(partial.status,400));
 const {ctx,els}=frontend('src/frontend/admin.js');ctx.fixture={template:{...t,field_mappings:{...mapping,targetLabels:['Date:'],selectedChoices:{'Date:':0}}},targetLabels:['Date:','Instrument'],matchResults:{'Date:':{candidates:[{location:{rowIdx:3,colIdx:5}}]}},docItems:[],docItemsCount:90};ctx.fetch=async()=>({json:async()=>ctx.fixture});ctx.renderMatcherTable=()=>{};els['matcher-select-template']={value:t.id};await vm.runInContext('runTemplateAnalyze()',ctx);check('saved field deletions and choices restored',()=>{assert.equal(vm.runInContext('currentMatcherData.targetLabels.join(",")',ctx),'Date:');assert.equal(vm.runInContext('currentMatcherData.selectedChoices["Date:"]',ctx),0)});
 // Directly exercise the real save serializer with full values, not its five display samples.
 const vals=Array.from({length:9},(_,i)=>String(i+1));const col=(idx)=>({location:{tableIdx:0,rowIdx:11,colIdx:idx},suggestedValueLocation:{type:'table_column',tableIdx:0,startRow:12,endRow:20,colIdx:idx},fullValues:vals,sampleValues:vals.slice(0,5)});
 ctx.fixture={template:t,targetLabels:['NIST Standard ℃ dp','Analyzer ℃ dp'],matchResults:{'NIST Standard ℃ dp':{candidates:[col(2)]},'Analyzer ℃ dp':{candidates:[col(3)]}},selectedChoices:{}};let payload;ctx.fetch=async(u,o)=>{payload=JSON.parse(o.body);return{ok:true,json:async()=>({success:true})}};vm.runInContext('currentMatcherData=fixture',ctx);await vm.runInContext('saveMatchedRules(false)',ctx);check('admin saves all 9 rows separately from single fields',()=>{assert.equal(payload.fieldMappings.testPoints.length,9);assert.equal(payload.fieldMappings.singleFields.length,0);assert.equal(payload.fieldMappings.testPoints[8].std,'9 ℃ dp')});
}finally{await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));db.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
